### ISSUE TITLE
Add checks for QC filtering

### ISSUE THREAD

**Issue by fasterius** [nf-core/spatialvi#46]
### Description of feature

Currently, the filtering of _e.g._ minimum counts or genes in the quality control report has no related checks to see if there are any spots lefter the filtering. Filtering itself will work just fine, but will produce non-informative errors downstream, which should be improved. The check should output an informative message about (1) what filtering step raised the problem, (2) what the relevant parameter was set to (either default or user-specified) and (3) that the user should re-run with a lowered threshold.

I'm not sure whether this type of check should stop the pipeline or not. Such errors currently _do_ yield errors that stop the pipeline, but we could also re-work the QC report in some fashion to still be able to output something - this could possibly be a useful functionality to have in regards to using _e.g._ `checkatlas` or `multiqc` for aggregating multiple reports as discussed in #40.

**Comment by grst** [comment]
I ran into this as well. The main problem was that the `in_tissue` column was parsed with the wrong dtype, leading to all spots being filtered out, no matter the threshold. 

This is fixed by this commit: https://github.com/nf-core/spatialtranscriptomics/pull/45/commits/8d1e5faeb23763d0e7c68936f01673352742ef3a

Regardless, I agree that it would be nice to catch the case when no spots are left.

**Comment by fasterius** [comment]
This is currently in the `dev` branch of the pipeline, implemented in such a way that it won't stop the pipeline but rather continue on without filtering as well as giving a notice to the user in the relevant report.
