### ISSUE TITLE
Auto-detection of samplesheet type

### ISSUE THREAD

**Issue by fasterius** [nf-core/spatialvi#47]
### Description of feature

The samplesheet is currently specified using `--input` as per standard nf-core practice, while defining whether that samplesheet describes data pre- or post-Space Ranger processing is done via the `--run_spaceranger` parameter. Another alternative is some kind of auto-detection of the samplesheet type, which could be done by checking the samplesheet header. Is this something that would be useful and help end-users, or would it just add hassle?

**Comment by grst** [comment]
Say we switch to specifying spaceranger output folders instead of files, as discussed in https://github.com/nf-core/spatialtranscriptomics/pull/45#discussion_r1221505471, the autodetection could simply be

 * spaceranger output directory column present in samplesheet -> continue with downstream
 * not present -> run spaceranger
