### ISSUE TITLE
Use `to_legacy_anndata` function from `spatialdata_io` instead of custom code

### ISSUE THREAD

**Issue by fasterius** [nf-core/spatialvi#75]
### Description of feature

We are currently using custom code as a work-around as a replacement for the `to_legacy_anndata` function from `spatialdata_io`, which did not exist when the work with SpatialData in this pipeline was initiated. This function is now merged in the SpatialData repo, but there is an issue with using it: https://github.com/scverse/spatialdata-io/issues/134.

As soon as this (and other possible issues) is fixed we should adopt the existing function instead of the custom one we have now.

**Comment by LucaMarconato** [comment]
Hi, I just fixed the linked issue. If you try the new `to_legacy_anndata()` please let us know in case the function needs some adjustments. We placed it under the `experimental` submodule because, as we encourage new packages not to rely on the legacy `AnnData` representation, we also didn't try using it in real world analyses, just in the ones we tested when developing the function (scanpy and squidpy).

**Comment by cavenel** [comment]
Looks like it is working now, I opened a PR with the updated function from `spatialdata-io` here: https://github.com/nf-core/spatialvi/pull/91
We can close this issue once the PR is merged (some docker version to fix first).
